### ISSUE TITLE
Pages added twice to archive after migrating from git to Dropbox

### ISSUE THREAD

**Issue by PetarPeychev** [davidmerfield/Blot#310] opened 2020-07-12 20:58 UTC
After moving my blog from git to Dropbox, the pre-existing files were not added to the Dropbox folder. I uploaded them manually to it and now the the archive contains two links to each post both pointing to the same page.

![screen](https://user-images.githubusercontent.com/33529197/87256428-6ce99600-c48a-11ea-83b0-9e8c978cfa90.png)

Removing / adding an underscore to the .md files in Dropbox removes the duplicate links, but the pages are also removed and the links point to nothing.

**Comment by PetarPeychev** [comment] 2020-07-12 22:16
I just noticed the main feed also has two copies of each article in the same order as in the archive.

**Comment by davidmerfield** [comment] 2020-07-14 17:07
Hello Petar – sorry for the delay – please consider emailing [support@blot.im](mailto:support@blot.im) for a more prompt response in future, I check email much more regularly than GitHub issues. I noticed that you reset your blog – is everything in order now?

---

As for the bug itself – this happens because Git is case-sensitive and Dropbox is not. The Dropbox client stores all its files in the lowercase. When transferring from Git to Dropbox. I will fix this and follow up with you

**Comment by PetarPeychev** [comment] 2020-07-14 17:11
Yeah, I did reset and fix it manually. Thanks for you support of the project, I will try to use the email if there are any more problems in the future.

**Comment by davidmerfield** [comment] 2020-07-20 20:33
I looked into this a little further and realized the problem is that there isn't a blocking 'transfer' stage when you connect the Dropbox client to an existing folder – there needs to be a progress bar which indicates as the files are transferring. 

> After moving my blog from git to Dropbox, the pre-existing files were not added to the Dropbox folder.

Did you encounter any errors when you were changing clients? Did a page load time out at any point?

**Comment by PetarPeychev** [comment] 2020-07-20 20:47
I don't recall anything like that, but I might not be remembering it.

**Comment by eg1776** [comment] 2020-08-15 12:31
I also ran into this issue.

**Comment by davidmerfield** [comment] 2020-08-17 15:25
@ericgregorich Same question to you: did you encounter any errors when you were changing clients? Did a page load time out at any point?

**Comment by ericgregorich** [comment] 2020-08-18 11:36
> @ericgregorich Same question to you: did you encounter any errors when you were changing clients? Did a page load time out at any point?

No errors. I just had written a single "Test" post. After switching from Git to Dropbox I then had a duplicate of that post. I only saw one in my files and on my account page. I deleted it but I still had one Test file remaining. I couldn't figure out where it was coming from so I just deleted the site and started over.

**Comment by davidmerfield** [comment] 2020-08-19 22:59
@ericgregorich Noted, thank you for the information

**Comment by davidmerfield** [comment] 2021-06-17 22:35
Minimal steps to reproduce in production:

1. Set up empty blog with git client
2. Add file whose name contains uppercase character, e.g. *Article.txt* 
3. Switch to Dropbox client
4. You now how two posts from Article.txt

**Comment by davidmerfield** [comment] 2021-06-18 16:08
This was fixed in #464 

Thank you all for the reports

**Comment by dvcrn** [comment] 2022-01-25 05:03
I ran into the same thing (in December 2021). A export of the entire site data shows that the same post exists twice, with identical guid. 

Even after I removed all posts from the blog it still displays the duplicates, but is not able to navigate to their detail page. The only way to resolve this was to wipe everything and start from scratch

Since this is quite recent it looks like https://github.com/davidmerfield/Blot/pull/464 did not fix the issue

**Comment by davidmerfield** [comment] 2023-03-20 19:41
This should now be solved by fixes I've made recently to `sync/lowerCaseContents`!

**Closed by davidmerfield** 2023-03-20 19:41 UTC
Labels: bug
